Grid system部分の実装
yu19921015/bulma_top_page pull request #4
Opened 2019-02-10 14:21 UTC by yu19921015

実装完了しました．
bulmaの練習なので，jsのロジックは組んでいません．
→add/removeを押しても何も起こりません．

レビューをよろしくお願いします．

2019-02-13 13:29 UTC, takao-sone requested changes
動かない（表示できない）...
コミット忘れかも。。。

2019-02-13 13:56 UTC, yu19921015 commented
やっぱり，Home.vueのコミット漏れでしたね．．．
ローカルのcommitまではやってたんだけど，pushを忘れてました．
申し訳ないです．．．

2019-02-14 11:31 UTC, yu19921015 commented
Home.vueのconflictを解消しました．
レビューとマージをお願いします．

2019-02-14 12:14 UTC, takao-sone commented
LGTMです！
初コンフリクト解消おつかれ！

2019-02-14 12:14 UTC, merged